KunstmaanNodeBundle_widgets:
    resource: "@KunstmaanNodeBundle/Controller/WidgetsController.php"
    type:     annotation
    prefix:   /admin/nodewidgets

KunstmaanNodeBundle_pages:
    resource: "@KunstmaanNodeBundle/Controller/PagesController.php"
    type:     annotation
    prefix:   /admin/pages

KunstmaanNodeBundle_slug:
    resource: "@KunstmaanNodeBundle/Controller/SlugController.php"
    type:     annotation
    prefix:   /