parameters:

services:
    nodetranslation.listener:
        class: Kunstmaan\AdminNodeBundle\Listener\NodeTranslationListener
        tags:
            - { name: doctrine.event_listener, event: onFlush, method: onFlush }
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }

    admin_menu.adaptor.pages:
        class: Kunstmaan\AdminNodeBundle\Helper\Menu\PageMenuAdaptor        
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@kunstmaan.acl.helper"]
        tags:
            -  { name: admin_menu.adaptor }
