services:
    kunstmaan_view.fix_date.listener:
        class: Kunstmaan\ViewBundle\EventListener\FixDateListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }