services:
    getpageparts.twig.extension:
        class: Kunstmaan\ViewBundle\Twig\Extension\GetPagepartsTwigExtension
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }
            
    trimhightlight.twig.extension:
        class: Kunstmaan\ViewBundle\Twig\Extension\TrimHighlightTwigExtension
        tags:
            - { name: twig.extension }
            