parameters:
    kunstmaan_node.version_timeout: 3600

services:
    kunstmaan_node.nodetranslation.listener:
        class: Kunstmaan\NodeBundle\EventListener\NodeTranslationListener
        tags:
            - { name: 'doctrine.event_listener', event: 'onFlush', method: 'onFlush' }
            - { name: 'doctrine.event_listener', event: 'postFlush', method: 'postFlush' }

    kunstmaan_node.menu.adaptor.pages:
        class: Kunstmaan\NodeBundle\Helper\Menu\PageMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@kunstmaan_admin.acl.helper"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
        
    kunstmaan_node.form.type.urlchooser:
        class: Kunstmaan\NodeBundle\Form\Type\URLChooserType
        tags:
            - { name: 'form.type', alias: 'urlchooser' }
            
    kunstmaan_node.form.type.slug:
        class: Kunstmaan\NodeBundle\Form\Type\SlugType
        tags:
            - { name: 'form.type', alias: 'slug' }

    kunstmaan_node.actions_menu_builder:
        class: Kunstmaan\NodeBundle\Helper\Menu\ActionsMenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@router", "@event_dispatcher", "@security.context"]

    kunstmaan_node.menu.sub_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kunstmaan_node.actions_menu_builder
        factory_method: createSubActionsMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: 'knp_menu.menu', alias: 'sub_actions' } # The alias is what is used to retrieve the menu

    kunstmaan_node.menu.actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kunstmaan_node.actions_menu_builder
        factory_method: createActionsMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: 'knp_menu.menu', alias: 'actions' } # The alias is what is used to retrieve the menu

    kunstmaan_node.menu.top_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kunstmaan_node.actions_menu_builder
        factory_method: createTopActionsMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: 'knp_menu.menu', alias: 'top_actions' } # The alias is what is used to retrieve the menu

    kunstmaan_node.fix_date.listener:
        class: Kunstmaan\NodeBundle\EventListener\FixDateListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }

    kunstmaan_node.tabs.twig.extension:
        class: Kunstmaan\NodeBundle\Twig\TabsTwigExtension
        tags:
            - { name: twig.extension }

    kunstmaan_node.edit_node.listener:
        class: Kunstmaan\NodeBundle\EventListener\NodeListener
        arguments: ["@security.context", "@kunstmaan_admin.permissionadmin", "@security.acl.permission.map"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

    kunstmaan_node.log_page_events.subscriber:
        class: Kunstmaan\NodeBundle\EventListener\LogPageEventsSubscriber
        arguments: ["@kunstmaan_admin.logger", "@security.context"]
        tags:
            - { name: kernel.event_subscriber }